### ISSUE TITLE
Making this repo a composer package.

### ISSUE THREAD

**Issue by rsm23** [rsm23/Online-Manga-Viewer#1]
Looking to make this repo a composer package, which means using autoloading, and PHP code standards ...

**Comment by lahiruhashan** [comment]
Explain your issue further. What is the problem you are aiming to address?

**Comment by rsm23** [comment]
@lahiruhashan I'm trying to make this a composer package, so that user's can use it on their projects (integrate it) on their existing PHP projects

**Comment by idoqo** [comment]
@rsm23 first, we would have to convert the `functions.inc.php` to a php class so they can work with composer autoload. I could do that if you would find time to test if it works.
